# only run for: merge commits, releases and pull-requests
#if: type != push OR branch = master OR branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/

stages:
  - name: pretest
  - name: test
  - name: deploy
    if: branch == travis

os: osx
language: swift
osx_image: xcode10.1
xcode_project: Path.swift.xcodeproj
xcode_scheme: Path.swift-Package
  
jobs:
  include:
    - stage: deploy
      name: Jazzy
      before_install: |
        cat << EOF > .jazzy.yaml
        module: Path
        module_version: $TRAVIS_TAG
        custom_categories:
          - name: Path
            children:
              - Path
              - /(_:_:)
        xcodebuild_arguments:
          - UseModernBuildSystem=NO
        output: output
        github_url: 'https://github.com/mxcl/Path.swift'
        EOF
        touch foo
      install: gem install jazzy
      before_script: swift package generate-xcodeproj
      script: jazzy
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: output
        on:
          tags: true

    - name: CocoaPods
      before_install: |
        cat << EOF > Path.swift.podspec
        Pod::Spec.new do |s|
          s.name             = 'Path.swift'
          s.version          = '$TRAVIS_TAG'
          s.summary          = 'Delightful, robust file-pathing functions'
          s.homepage         = 'https://github.com/mxcl/Path.swift'
          s.license          = { :type => 'Unlicense', :file => 'LICENSE.md' }
          s.author           = { 'mxcl' => 'mxcl@me.com' }
          s.source           = { :git => 'https://github.com/mxcl/Path.swift.git', :tag => s.version.to_s }
          s.social_media_url = 'https://twitter.com/mxcl'
          s.osx.deployment_target = '10.10'
          s.ios.deployment_target = '8.0'
          s.tvos.deployment_target = '10.0'
          s.watchos.deployment_target = '3.0'
          s.source_files = 'Sources/*'
          s.swift_version = '4.2'
        end
        EOF
        touch foo
      install: gem install cocoapods --pre
      script: pod lib lint
